/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/auth/otp/send": {
    /** Send Otp */
    post: operations["send_otp_api_v1_auth_otp_send_post"];
  };
  "/api/v1/auth/otp/verify": {
    /** Verify Otp */
    post: operations["verify_otp_api_v1_auth_otp_verify_post"];
  };
  "/api/v1/auth/firebase": {
    /** Firebase Auth */
    post: operations["firebase_auth_api_v1_auth_firebase_post"];
  };
  "/api/v1/auth/refresh": {
    /** Refresh Token */
    post: operations["refresh_token_api_v1_auth_refresh_post"];
  };
  "/api/v1/auth/logout": {
    /** Logout */
    post: operations["logout_api_v1_auth_logout_post"];
  };
  "/api/v1/auth/me": {
    /** Get Me */
    get: operations["get_me_api_v1_auth_me_get"];
  };
  "/api/v1/auth/me/account": {
    /** Get Account */
    get: operations["get_account_api_v1_auth_me_account_get"];
    /** Update Account */
    patch: operations["update_account_api_v1_auth_me_account_patch"];
  };
  "/api/v1/auth/device-token": {
    /** Register Device Token */
    post: operations["register_device_token_api_v1_auth_device_token_post"];
  };
  "/api/v1/auth/.well-known/jwks.json": {
    /** Public Key */
    get: operations["public_key_api_v1_auth__well_known_jwks_json_get"];
  };
  "/api/v1/kyc/initiate": {
    /** Initiate Kyc */
    post: operations["initiate_kyc_api_v1_kyc_initiate_post"];
  };
  "/api/v1/kyc/documents/{document_id}/submit": {
    /** Submit Kyc */
    post: operations["submit_kyc_api_v1_kyc_documents__document_id__submit_post"];
  };
  "/api/v1/kyc/status": {
    /** Kyc Status */
    get: operations["kyc_status_api_v1_kyc_status_get"];
  };
  "/api/v1/kyc/documents/{document_id}/process": {
    /** Process Kyc */
    post: operations["process_kyc_api_v1_kyc_documents__document_id__process_post"];
  };
  "/api/v1/listings": {
    /** List Listings */
    get: operations["list_listings_api_v1_listings_get"];
    /** Post Listing */
    post: operations["post_listing_api_v1_listings_post"];
  };
  "/api/v1/listings/{unit_id}": {
    /** Get Listing */
    get: operations["get_listing_api_v1_listings__unit_id__get"];
    /** Patch Listing */
    patch: operations["patch_listing_api_v1_listings__unit_id__patch"];
  };
  "/api/v1/listings/{unit_id}/availability": {
    /** Get Listing Availability */
    get: operations["get_listing_availability_api_v1_listings__unit_id__availability_get"];
  };
  "/api/v1/listings/{unit_id}/publish": {
    /** Post Publish Listing */
    post: operations["post_publish_listing_api_v1_listings__unit_id__publish_post"];
  };
  "/api/v1/listings/{unit_id}/unpublish": {
    /** Post Unpublish Listing */
    post: operations["post_unpublish_listing_api_v1_listings__unit_id__unpublish_post"];
  };
  "/api/v1/listings/{unit_id}/archive": {
    /** Post Archive Listing */
    post: operations["post_archive_listing_api_v1_listings__unit_id__archive_post"];
  };
  "/api/v1/listings/{unit_id}/calendar": {
    /** Post Host Calendar Rule */
    post: operations["post_host_calendar_rule_api_v1_listings__unit_id__calendar_post"];
  };
  "/api/v1/listings/{unit_id}/calendar/{rule_id}": {
    /** Delete Host Calendar Rule Endpoint */
    delete: operations["delete_host_calendar_rule_endpoint_api_v1_listings__unit_id__calendar__rule_id__delete"];
    /** Patch Host Calendar Rule */
    patch: operations["patch_host_calendar_rule_api_v1_listings__unit_id__calendar__rule_id__patch"];
  };
  "/api/v1/listings/{unit_id}/calendar/bulk-availability": {
    /** Post Bulk Availability */
    post: operations["post_bulk_availability_api_v1_listings__unit_id__calendar_bulk_availability_post"];
  };
  "/api/v1/listings/{unit_id}/calendar/bulk-pricing": {
    /** Post Bulk Pricing */
    post: operations["post_bulk_pricing_api_v1_listings__unit_id__calendar_bulk_pricing_post"];
  };
  "/api/v1/listings/host/dashboard": {
    /** Get Host Dashboard Endpoint */
    get: operations["get_host_dashboard_endpoint_api_v1_listings_host_dashboard_get"];
  };
  "/api/v1/listings/host/reservations": {
    /** Get Host Reservations Endpoint */
    get: operations["get_host_reservations_endpoint_api_v1_listings_host_reservations_get"];
  };
  "/api/v1/availability/{unit_id}": {
    /** Get Unit Availability */
    get: operations["get_unit_availability_api_v1_availability__unit_id__get"];
    /** Patch Unit Availability */
    patch: operations["patch_unit_availability_api_v1_availability__unit_id__patch"];
  };
  "/api/v1/operations/tasks": {
    /** Post Task */
    post: operations["post_task_api_v1_operations_tasks_post"];
  };
  "/api/v1/operations/tasks/{task_id}": {
    /** Get Task Endpoint */
    get: operations["get_task_endpoint_api_v1_operations_tasks__task_id__get"];
    /** Patch Task */
    patch: operations["patch_task_api_v1_operations_tasks__task_id__patch"];
  };
  "/api/v1/operations/tasks/{task_id}/assign": {
    /** Post Assign Task */
    post: operations["post_assign_task_api_v1_operations_tasks__task_id__assign_post"];
  };
  "/api/v1/operations/tasks/{task_id}/start": {
    /** Post Start Task */
    post: operations["post_start_task_api_v1_operations_tasks__task_id__start_post"];
  };
  "/api/v1/operations/tasks/{task_id}/complete": {
    /** Post Complete Task */
    post: operations["post_complete_task_api_v1_operations_tasks__task_id__complete_post"];
  };
  "/api/v1/operations/tasks/{task_id}/notes": {
    /** Post Task Note */
    post: operations["post_task_note_api_v1_operations_tasks__task_id__notes_post"];
  };
  "/api/v1/operations/tasks/{task_id}/attachments": {
    /** Post Task Attachment */
    post: operations["post_task_attachment_api_v1_operations_tasks__task_id__attachments_post"];
  };
  "/api/v1/operations/tasks/{task_id}/timeline": {
    /** Get Task Timeline Endpoint */
    get: operations["get_task_timeline_endpoint_api_v1_operations_tasks__task_id__timeline_get"];
  };
  "/api/v1/operations/staff": {
    /** Get Field Staff */
    get: operations["get_field_staff_api_v1_operations_staff_get"];
    /** Post Field Staff */
    post: operations["post_field_staff_api_v1_operations_staff_post"];
  };
  "/api/v1/operations/maintenance": {
    /** List Maintenance Requests */
    get: operations["list_maintenance_requests_api_v1_operations_maintenance_get"];
    /** Post Maintenance Request */
    post: operations["post_maintenance_request_api_v1_operations_maintenance_post"];
  };
  "/api/v1/operations/maintenance/{request_id}": {
    /** Get Maintenance Request Endpoint */
    get: operations["get_maintenance_request_endpoint_api_v1_operations_maintenance__request_id__get"];
    /** Patch Maintenance Request */
    patch: operations["patch_maintenance_request_api_v1_operations_maintenance__request_id__patch"];
  };
  "/api/v1/operations/readiness/{unit_id}": {
    /** Get Readiness */
    get: operations["get_readiness_api_v1_operations_readiness__unit_id__get"];
    /** Patch Readiness */
    patch: operations["patch_readiness_api_v1_operations_readiness__unit_id__patch"];
  };
  "/api/v1/operations/dashboard": {
    /** Get Dashboard */
    get: operations["get_dashboard_api_v1_operations_dashboard_get"];
  };
  "/api/v1/operations/recurring-maintenance": {
    /** Post Recurring Maintenance */
    post: operations["post_recurring_maintenance_api_v1_operations_recurring_maintenance_post"];
  };
  "/api/v1/reservations": {
    /** Get Reservations */
    get: operations["get_reservations_api_v1_reservations_get"];
    /** Post Reservation */
    post: operations["post_reservation_api_v1_reservations_post"];
  };
  "/api/v1/reservations/{reservation_id}": {
    /** Get Reservation Detail */
    get: operations["get_reservation_detail_api_v1_reservations__reservation_id__get"];
  };
  "/api/v1/reservations/{reservation_id}/confirm": {
    /** Post Confirm Reservation */
    post: operations["post_confirm_reservation_api_v1_reservations__reservation_id__confirm_post"];
  };
  "/api/v1/reservations/{reservation_id}/cancel": {
    /** Post Cancel Reservation */
    post: operations["post_cancel_reservation_api_v1_reservations__reservation_id__cancel_post"];
  };
  "/api/v1/reservations/{reservation_id}/check-in": {
    /** Post Check In */
    post: operations["post_check_in_api_v1_reservations__reservation_id__check_in_post"];
  };
  "/api/v1/reservations/{reservation_id}/check-out": {
    /** Post Check Out */
    post: operations["post_check_out_api_v1_reservations__reservation_id__check_out_post"];
  };
  "/api/v1/reservations/{reservation_id}/promo": {
    /** Post Apply Promo */
    post: operations["post_apply_promo_api_v1_reservations__reservation_id__promo_post"];
  };
  "/api/v1/bookings": {
    /** Get Host Bookings */
    get: operations["get_host_bookings_api_v1_bookings_get"];
    /** Post Booking */
    post: operations["post_booking_api_v1_bookings_post"];
  };
  "/api/v1/bookings/{booking_id}": {
    /** Get Booking Detail */
    get: operations["get_booking_detail_api_v1_bookings__booking_id__get"];
    /** Patch Booking */
    patch: operations["patch_booking_api_v1_bookings__booking_id__patch"];
  };
  "/api/v1/finance/wallets/me": {
    /** Get My Wallet */
    get: operations["get_my_wallet_api_v1_finance_wallets_me_get"];
  };
  "/api/v1/finance/wallets/{wallet_id}/ledger": {
    /** List Wallet Ledger */
    get: operations["list_wallet_ledger_api_v1_finance_wallets__wallet_id__ledger_get"];
  };
  "/api/v1/finance/escrow": {
    /** List Escrows */
    get: operations["list_escrows_api_v1_finance_escrow_get"];
  };
  "/api/v1/finance/escrow/{escrow_id}": {
    /** Get Escrow */
    get: operations["get_escrow_api_v1_finance_escrow__escrow_id__get"];
  };
  "/api/v1/finance/escrow/{escrow_id}/release": {
    /** Release Escrow Endpoint */
    post: operations["release_escrow_endpoint_api_v1_finance_escrow__escrow_id__release_post"];
  };
  "/api/v1/finance/escrow/{escrow_id}/hold": {
    /** Hold Escrow Endpoint */
    post: operations["hold_escrow_endpoint_api_v1_finance_escrow__escrow_id__hold_post"];
  };
  "/api/v1/finance/payouts": {
    /** List Payouts */
    get: operations["list_payouts_api_v1_finance_payouts_get"];
    /** Create Payout Request */
    post: operations["create_payout_request_api_v1_finance_payouts_post"];
  };
  "/api/v1/finance/payouts/{payout_id}/process": {
    /** Process Payout Endpoint */
    post: operations["process_payout_endpoint_api_v1_finance_payouts__payout_id__process_post"];
  };
  "/api/v1/finance/webhooks/paymob": {
    /** Paymob Webhook */
    post: operations["paymob_webhook_api_v1_finance_webhooks_paymob_post"];
  };
  "/api/v1/finance/webhooks/stripe": {
    /** Stripe Webhook */
    post: operations["stripe_webhook_api_v1_finance_webhooks_stripe_post"];
  };
  "/health": {
    /** Health Check */
    get: operations["health_check_health_get"];
  };
  "/health/live": {
    /** Liveness Check */
    get: operations["liveness_check_health_live_get"];
  };
  "/health/ready": {
    /** Readiness Check */
    get: operations["readiness_check_health_ready_get"];
  };
  "/health/deep": {
    /** Deep Health Check */
    get: operations["deep_health_check_health_deep_get"];
  };
  "/metrics": {
    /** Metrics */
    get: operations["metrics_metrics_get"];
  };
  "/version": {
    /** Version */
    get: operations["version_version_get"];
  };
  "/": {
    /** Root */
    get: operations["root__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AccountResponse */
    AccountResponse: {
      /** Id */
      id: string;
      /** User Id */
      user_id: string;
      /** Legal Name */
      legal_name: string | null;
      /** National Id */
      national_id: string | null;
      /** Date Of Birth */
      date_of_birth: string | null;
      /** Tax Id */
      tax_id: string | null;
      /** Address */
      address: {
        [key: string]: unknown;
      } | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** AccountUpdate */
    AccountUpdate: {
      /** Legal Name */
      legal_name?: string | null;
      /** National Id */
      national_id?: string | null;
      /** Date Of Birth */
      date_of_birth?: string | null;
      /** Tax Id */
      tax_id?: string | null;
      /** Address */
      address?: {
        [key: string]: unknown;
      } | null;
    };
    /** AvailabilityDay */
    AvailabilityDay: {
      /**
       * Date
       * Format: date
       */
      date: string;
      /** Status */
      status: string;
      /** Block Type */
      block_type?: string | null;
    };
    /** AvailabilityRule */
    AvailabilityRule: {
      /**
       * Date From
       * Format: date
       */
      date_from: string;
      /**
       * Date To
       * Format: date
       */
      date_to: string;
      status: components["schemas"]["AvailabilityStatus"];
    };
    /**
     * AvailabilityStatus
     * @enum {string}
     */
    AvailabilityStatus: "available" | "blocked" | "booked" | "hold";
    /** AvailabilityUpdateRequest */
    AvailabilityUpdateRequest: {
      /** Rules */
      rules: components["schemas"]["AvailabilityRule"][];
    };
    /** AvailabilityUpdateResponse */
    AvailabilityUpdateResponse: {
      /** Rules */
      rules: components["schemas"]["app__availability__schemas__CalendarRuleResponse"][];
    };
    /** Body_list_listings_api_v1_listings_get */
    Body_list_listings_api_v1_listings_get: {
      /** Property Type */
      property_type?: string[] | null;
      /** Cultural Tags */
      cultural_tags?: string[] | null;
      /** Amenities */
      amenities?: string[] | null;
    };
    /** BookingCreate */
    BookingCreate: {
      /** Unit Id */
      unit_id: string;
      /**
       * Check In
       * Format: date
       */
      check_in: string;
      /**
       * Check Out
       * Format: date
       */
      check_out: string;
      /**
       * Adults
       * @default 1
       */
      adults?: number;
      /**
       * Children
       * @default 0
       */
      children?: number;
      /**
       * Infants
       * @default 0
       */
      infants?: number;
    };
    /** BookingResponse */
    BookingResponse: {
      /** Id */
      id: string;
      /** Unit Id */
      unit_id: string;
      /** Guest Id */
      guest_id: string;
      /** Host Id */
      host_id?: string | null;
      /** Status */
      status: string;
      /**
       * Check In
       * Format: date
       */
      check_in: string;
      /**
       * Check Out
       * Format: date
       */
      check_out: string;
      /** Adults */
      adults: number;
      /** Children */
      children: number;
      /** Infants */
      infants: number;
      /**
       * Requested At
       * Format: date-time
       */
      requested_at: string;
      /** Accepted At */
      accepted_at: string | null;
      /** Rejected At */
      rejected_at: string | null;
      /** Cancelled At */
      cancelled_at: string | null;
      /** Reject Reason */
      reject_reason: string | null;
      /** Cancel Reason */
      cancel_reason: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * BookingStatus
     * @enum {string}
     */
    BookingStatus: "requested" | "accepted" | "confirmed" | "rejected" | "cancelled";
    /** BookingUpdate */
    BookingUpdate: {
      status: components["schemas"]["BookingStatus"];
      /** Reject Reason */
      reject_reason?: string | null;
      /** Cancel Reason */
      cancel_reason?: string | null;
    };
    /** BulkAvailabilityRequest */
    BulkAvailabilityRequest: {
      /** Rules */
      rules: components["schemas"]["BulkCalendarItem"][];
    };
    /** BulkCalendarItem */
    BulkCalendarItem: {
      /**
       * Date From
       * Format: date
       */
      date_from: string;
      /**
       * Date To
       * Format: date
       */
      date_to: string;
      /** Status */
      status: string;
      /** Block Type */
      block_type?: string | null;
    };
    /** BulkPricingItem */
    BulkPricingItem: {
      /**
       * Date From
       * Format: date
       */
      date_from: string;
      /**
       * Date To
       * Format: date
       */
      date_to: string;
      /** Price Override */
      price_override: number;
    };
    /** BulkPricingRequest */
    BulkPricingRequest: {
      /** Rules */
      rules: components["schemas"]["BulkPricingItem"][];
    };
    /** CalendarDay */
    CalendarDay: {
      /**
       * Date
       * Format: date
       */
      date: string;
      /** Status */
      status: string;
      /** Block Type */
      block_type?: string | null;
      /** Price Egp */
      price_egp: number;
    };
    /** CalendarRuleCreate */
    CalendarRuleCreate: {
      /**
       * Date From
       * Format: date
       */
      date_from: string;
      /**
       * Date To
       * Format: date
       */
      date_to: string;
      /** Status */
      status: string;
      /** Block Type */
      block_type?: string | null;
      /** Price Override */
      price_override?: number | null;
    };
    /** CalendarRuleUpdate */
    CalendarRuleUpdate: {
      /** Date From */
      date_from?: string | null;
      /** Date To */
      date_to?: string | null;
      /** Status */
      status?: string | null;
      /** Block Type */
      block_type?: string | null;
      /** Price Override */
      price_override?: number | null;
    };
    /**
     * CancellationReason
     * @enum {string}
     */
    CancellationReason: "change_of_plans" | "emergency" | "host_request" | "admin_request" | "payment_failure" | "fraud" | "other";
    /** ChecklistItem */
    ChecklistItem: {
      /** Item */
      item: string;
      /**
       * Completed
       * @default false
       */
      completed?: boolean;
    };
    /** DeviceTokenRegisterRequest */
    DeviceTokenRegisterRequest: {
      /** Token */
      token: string;
      /** Platform */
      platform: string;
      /** App Version */
      app_version?: string | null;
    };
    /** DeviceTokenResponse */
    DeviceTokenResponse: {
      /** Id */
      id: string;
      /** User Id */
      user_id: string;
      /** Platform */
      platform: string;
      /** App Version */
      app_version: string | null;
      /** Is Active */
      is_active: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** EscrowListResponse */
    EscrowListResponse: {
      /**
       * Success
       * @default true
       */
      success?: boolean;
      /** Message */
      message?: string | null;
      /** Data */
      data: components["schemas"]["EscrowResponse"][];
    };
    /** EscrowResponse */
    EscrowResponse: {
      /** Id */
      id: string;
      /** Reservation Id */
      reservation_id: string;
      /** Host Id */
      host_id: string;
      /** Amount Egp */
      amount_egp: number;
      /** Status */
      status: string;
      /** Hold Until */
      hold_until: string | null;
      /** Released At */
      released_at: string | null;
      /** Refunded At */
      refunded_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** FieldStaffCreate */
    FieldStaffCreate: {
      /** User Id */
      user_id?: string | null;
      /** Name */
      name: string;
      /** Phone */
      phone?: string | null;
      role: components["schemas"]["StaffRole"];
      /**
       * Is Active
       * @default true
       */
      is_active?: boolean;
    };
    /** FieldStaffResponse */
    FieldStaffResponse: {
      /** Id */
      id: string;
      /** User Id */
      user_id?: string | null;
      /** Name */
      name: string;
      /** Phone */
      phone?: string | null;
      role: components["schemas"]["StaffRole"];
      /** Is Active */
      is_active: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** FirebaseAuthRequest */
    FirebaseAuthRequest: {
      /** Id Token */
      id_token: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Status */
      status: string;
      /** Database */
      database: string;
      /** Redis */
      redis: string;
    };
    /** HostDashboardStats */
    HostDashboardStats: {
      /** Total Listings */
      total_listings: number;
      /** Listed Listings */
      listed_listings: number;
      /** Total Reservations */
      total_reservations: number;
      /** Upcoming Reservations */
      upcoming_reservations: number;
      /** Total Revenue Egp */
      total_revenue_egp: number;
      /** Occupancy Rate Pct */
      occupancy_rate_pct: number;
    };
    /** HostReservationCalendarItem */
    HostReservationCalendarItem: {
      /** Reservation Id */
      reservation_id: string;
      /** Unit Id */
      unit_id: string;
      /** Guest Id */
      guest_id: string;
      /** Status */
      status: string;
      /**
       * Check In
       * Format: date
       */
      check_in: string;
      /**
       * Check Out
       * Format: date
       */
      check_out: string;
      /** Total Amount Egp */
      total_amount_egp: number;
    };
    /** HostReservationCalendarResponse */
    HostReservationCalendarResponse: {
      /** Unit Id */
      unit_id: string;
      /**
       * Check In
       * Format: date
       */
      check_in: string;
      /**
       * Check Out
       * Format: date
       */
      check_out: string;
      /** Reservations */
      reservations: components["schemas"]["HostReservationCalendarItem"][];
    };
    /** KycDocumentResponse */
    KycDocumentResponse: {
      /** Id */
      id: string;
      /** User Id */
      user_id: string;
      /** Account Id */
      account_id: string | null;
      document_type: components["schemas"]["KycDocumentType"];
      /** Document Number */
      document_number: string | null;
      status: components["schemas"]["KycStatus"];
      /** Legal Name */
      legal_name: string | null;
      /** Front Image Key */
      front_image_key: string | null;
      /** Back Image Key */
      back_image_key: string | null;
      /** Selfie Image Key */
      selfie_image_key: string | null;
      /** Verified At */
      verified_at: string | null;
      /** Rejected At */
      rejected_at: string | null;
      /** Rejection Reason */
      rejection_reason: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * KycDocumentType
     * @enum {string}
     */
    KycDocumentType: "passport" | "national_id" | "driving_license";
    /** KycInitiateRequest */
    KycInitiateRequest: {
      document_type: components["schemas"]["KycDocumentType"];
      /** Document Number */
      document_number?: string | null;
    };
    /** KycInitiateResponse */
    KycInitiateResponse: {
      /** Document Id */
      document_id: string;
      upload_urls: components["schemas"]["KycUploadUrls"];
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
    };
    /**
     * KycStatus
     * @enum {string}
     */
    KycStatus: "unverified" | "pending" | "verified" | "rejected";
    /** KycStatusResponse */
    KycStatusResponse: {
      /** User Id */
      user_id: string;
      kyc_status: components["schemas"]["KycStatus"];
      /** Documents */
      documents: components["schemas"]["KycDocumentResponse"][];
    };
    /** KycSubmitResponse */
    KycSubmitResponse: {
      /** Document Id */
      document_id: string;
      status: components["schemas"]["KycStatus"];
    };
    /** KycUploadUrls */
    KycUploadUrls: {
      /** Front */
      front: string;
      /** Back */
      back: string;
      /** Selfie */
      selfie: string;
    };
    /** LedgerEntryResponse */
    LedgerEntryResponse: {
      /** Id */
      id: string;
      /** Transaction Id */
      transaction_id: string;
      /** Wallet Id */
      wallet_id: string | null;
      /** Escrow Id */
      escrow_id: string | null;
      /** Ledger Account */
      ledger_account: string;
      /** Account Type */
      account_type: string;
      /** Entry Type */
      entry_type: string;
      /** Amount Egp */
      amount_egp: number;
      /** Balance After */
      balance_after: number;
      /** Description */
      description: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** LedgerListResponse */
    LedgerListResponse: {
      /**
       * Success
       * @default true
       */
      success?: boolean;
      /** Message */
      message?: string | null;
      /** Data */
      data: components["schemas"]["LedgerEntryResponse"][];
    };
    /** ListingCreate */
    ListingCreate: {
      /** Property Type */
      property_type: string;
      /** Lat */
      lat: number;
      /** Lng */
      lng: number;
      /** Governorate */
      governorate: string;
      /** City */
      city: string;
      /** District */
      district?: string | null;
      /** Google Place Id */
      google_place_id?: string | null;
      /** Max Guests */
      max_guests: number;
      /** Bedrooms */
      bedrooms: number;
      /** Bathrooms */
      bathrooms: number;
      /** Title Ar */
      title_ar: string;
      /** Title En */
      title_en?: string | null;
      /** Description Ar */
      description_ar: string;
      /** Description En */
      description_en?: string | null;
      /** Amenities */
      amenities?: string[];
      /** Cultural Tags */
      cultural_tags?: string[];
      /** Base Price Egp */
      base_price_egp: number;
      /**
       * Weekend Mult
       * @default 1
       */
      weekend_mult?: number;
      /**
       * Peak Mult
       * @default 1
       */
      peak_mult?: number;
      /**
       * Min Nights
       * @default 1
       */
      min_nights?: number;
      /**
       * Max Nights
       * @default 30
       */
      max_nights?: number;
      /** House Rules */
      house_rules?: string | null;
      /** Check In Instructions */
      check_in_instructions?: string | null;
      /** Policies */
      policies?: string | null;
      /**
       * Country
       * @default Egypt
       */
      country?: string;
      /**
       * Currency
       * @default EGP
       */
      currency?: string;
      /** Cover Photo Id */
      cover_photo_id?: string | null;
      /**
       * Is Draft
       * @default false
       */
      is_draft?: boolean;
    };
    /** ListingResponse */
    ListingResponse: {
      /** Id */
      id: string;
      /** Host Id */
      host_id: string;
      /** Host Display Name */
      host_display_name: string | null;
      /** Host Kyc Status */
      host_kyc_status: string | null;
      /** Host Joined At */
      host_joined_at: string | null;
      /** Property Type */
      property_type: string;
      /** Status */
      status: string;
      /** Lat */
      lat: number;
      /** Lng */
      lng: number;
      /** Governorate */
      governorate: string;
      /** City */
      city: string;
      /** Country */
      country: string;
      /** District */
      district: string | null;
      /** Address */
      address: string | null;
      /** Max Guests */
      max_guests: number;
      /** Bedrooms */
      bedrooms: number;
      /** Beds */
      beds: number;
      /** Bathrooms */
      bathrooms: number;
      /** Category */
      category: string;
      /** Title Ar */
      title_ar: string;
      /** Title En */
      title_en: string | null;
      /** Title */
      title: string;
      /** Description Ar */
      description_ar: string;
      /** Description En */
      description_en: string | null;
      /** Description */
      description: string;
      /** Amenities */
      amenities: string[];
      /** Cultural Tags */
      cultural_tags: string[];
      /** Base Price Egp */
      base_price_egp: number;
      /** Cleaning Fee Egp */
      cleaning_fee_egp: number;
      /** Cancellation Policy */
      cancellation_policy: string;
      /** Price */
      price: number;
      /** Currency */
      currency: string;
      /** Weekend Mult */
      weekend_mult: number;
      /** Peak Mult */
      peak_mult: number;
      /** Min Nights */
      min_nights: number;
      /** Max Nights */
      max_nights: number;
      /** House Rules */
      house_rules: string | null;
      /** Check In Instructions */
      check_in_instructions: string | null;
      /** Policies */
      policies: string | null;
      /** Cover Image */
      cover_image?: string | null;
    };
    /** ListingSearchResponse */
    ListingSearchResponse: {
      /** Data */
      data: components["schemas"]["ListingSearchResult"][];
      pagination: components["schemas"]["PaginationInfo"];
    };
    /** ListingSearchResult */
    ListingSearchResult: {
      /** Id */
      id: string;
      /** Title Ar */
      title_ar: string;
      /** Title En */
      title_en: string | null;
      /** Title */
      title: string;
      /** Description */
      description: string;
      /** Property Type */
      property_type: string;
      /** City */
      city: string;
      /** Governorate */
      governorate: string;
      /** Country */
      country: string;
      /** Base Price Egp */
      base_price_egp: number;
      /** Price */
      price: number;
      /** Currency */
      currency: string;
      /** Lat */
      lat: number;
      /** Lng */
      lng: number;
      /** Max Guests */
      max_guests: number;
      /** Bedrooms */
      bedrooms: number;
      /** Bathrooms */
      bathrooms: number;
      /** Amenities */
      amenities: string[];
      /** Cultural Tags */
      cultural_tags: string[];
      /** House Rules */
      house_rules: string | null;
      /** Host Kyc Status */
      host_kyc_status: string | null;
      /** Cover Image */
      cover_image?: string | null;
    };
    /** ListingUpdate */
    ListingUpdate: {
      /** Title Ar */
      title_ar?: string | null;
      /** Title En */
      title_en?: string | null;
      /** Description Ar */
      description_ar?: string | null;
      /** Description En */
      description_en?: string | null;
      /** Amenities */
      amenities?: string[] | null;
      /** Cultural Tags */
      cultural_tags?: string[] | null;
      /** Base Price Egp */
      base_price_egp?: number | null;
      /** Weekend Mult */
      weekend_mult?: number | null;
      /** Peak Mult */
      peak_mult?: number | null;
      /** Min Nights */
      min_nights?: number | null;
      /** Max Nights */
      max_nights?: number | null;
      /** House Rules */
      house_rules?: string | null;
      /** Check In Instructions */
      check_in_instructions?: string | null;
      /** Policies */
      policies?: string | null;
      /** Country */
      country?: string | null;
      /** Currency */
      currency?: string | null;
      /** Cover Photo Id */
      cover_photo_id?: string | null;
    };
    /** MaintenanceRequestCreate */
    MaintenanceRequestCreate: {
      /** Unit Id */
      unit_id: string;
      /** Issue Type */
      issue_type: string;
      /** Description */
      description: string;
      /** Reporter Id */
      reporter_id?: string | null;
    };
    /** MaintenanceRequestResponse */
    MaintenanceRequestResponse: {
      /** Id */
      id: string;
      /** Unit Id */
      unit_id: string;
      /** Reporter Id */
      reporter_id?: string | null;
      /** Issue Type */
      issue_type: string;
      /** Description */
      description: string;
      status: components["schemas"]["MaintenanceRequestStatus"];
      /** Related Task Id */
      related_task_id?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * MaintenanceRequestStatus
     * @enum {string}
     */
    MaintenanceRequestStatus: "OPEN" | "IN_PROGRESS" | "RESOLVED" | "CANCELLED";
    /** MaintenanceRequestUpdate */
    MaintenanceRequestUpdate: {
      status?: components["schemas"]["MaintenanceRequestStatus"] | null;
      /** Related Task Id */
      related_task_id?: string | null;
    };
    /** OperationsDashboardResponse */
    OperationsDashboardResponse: {
      /** Pending Tasks */
      pending_tasks: number;
      /** In Progress Tasks */
      in_progress_tasks: number;
      /** Completed Tasks Today */
      completed_tasks_today: number;
      /** Overdue Tasks */
      overdue_tasks: number;
      /** Open Maintenance Requests */
      open_maintenance_requests: number;
      /** Not Ready Units */
      not_ready_units: number;
      /** Active Field Staff */
      active_field_staff: number;
    };
    /** OtpSendRequest */
    OtpSendRequest: {
      /** Phone Number */
      phone_number: string;
    };
    /** OtpSendResponse */
    OtpSendResponse: {
      /** Phone Number */
      phone_number: string;
      /** Status */
      status: string;
    };
    /** OtpVerifyRequest */
    OtpVerifyRequest: {
      /** Phone Number */
      phone_number: string;
      /** Code */
      code: string;
    };
    /** PaginationInfo */
    PaginationInfo: {
      /** Next Cursor */
      next_cursor: string | null;
      /** Has More */
      has_more: boolean;
      /** Total Count */
      total_count: number;
    };
    /** PaymentConfirmationRequest */
    PaymentConfirmationRequest: {
      provider: components["schemas"]["PaymentProvider"];
      /** Provider Ref */
      provider_ref: string;
    };
    /** PaymentIntentResponse */
    PaymentIntentResponse: {
      /** Id */
      id: string;
      /** Reservation Id */
      reservation_id: string;
      /** Provider */
      provider: string;
      /** Provider Ref */
      provider_ref: string;
      /** Amount Egp */
      amount_egp: number;
      /** Status */
      status: string;
      /** Provider Metadata */
      provider_metadata?: {
        [key: string]: unknown;
      } | null;
      /** Captured At */
      captured_at: string | null;
    };
    /**
     * PaymentMethod
     * @enum {string}
     */
    PaymentMethod: "fawry" | "meeza" | "vodafone_cash" | "card";
    /**
     * PaymentProvider
     * @enum {string}
     */
    PaymentProvider: "paymob" | "stripe";
    /** PayoutListResponse */
    PayoutListResponse: {
      /**
       * Success
       * @default true
       */
      success?: boolean;
      /** Message */
      message?: string | null;
      /** Data */
      data: components["schemas"]["PayoutRequestResponse"][];
    };
    /** PayoutProcessRequest */
    PayoutProcessRequest: {
      /**
       * Provider
       * @default paymob
       */
      provider?: string;
    };
    /** PayoutRequestCreate */
    PayoutRequestCreate: {
      /** Amount Egp */
      amount_egp: number;
      /** Bank Account Info */
      bank_account_info: {
        [key: string]: unknown;
      };
    };
    /** PayoutRequestResponse */
    PayoutRequestResponse: {
      /** Id */
      id: string;
      /** Wallet Id */
      wallet_id: string;
      /** Host Id */
      host_id: string;
      /** Amount Egp */
      amount_egp: number;
      /** Status */
      status: string;
      /** Provider */
      provider: string | null;
      /** Provider Ref */
      provider_ref: string | null;
      /** Processed At */
      processed_at: string | null;
      /** Failure Reason */
      failure_reason: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** PromoApplicationResponse */
    PromoApplicationResponse: {
      /** Id */
      id: string;
      /** Reservation Id */
      reservation_id: string;
      /** Promo Code Id */
      promo_code_id: string;
      /** Discount Pct */
      discount_pct: number;
      /** Discount Amount Egp */
      discount_amount_egp: number;
    };
    /** PromoApplyRequest */
    PromoApplyRequest: {
      /** Code */
      code: string;
    };
    /** PropertyReadinessResponse */
    PropertyReadinessResponse: {
      /** Id */
      id: string;
      /** Unit Id */
      unit_id: string;
      /** Reservation Id */
      reservation_id?: string | null;
      status: components["schemas"]["ReadinessStatus"];
      /** Blocked Until */
      blocked_until?: string | null;
      /** Reason */
      reason?: string | null;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** PropertyReadinessUpdate */
    PropertyReadinessUpdate: {
      status: components["schemas"]["ReadinessStatus"];
      /** Blocked Until */
      blocked_until?: string | null;
      /** Reason */
      reason?: string | null;
    };
    /**
     * ReadinessStatus
     * @enum {string}
     */
    ReadinessStatus: "NOT_READY" | "READY";
    /**
     * RecurringFrequency
     * @enum {string}
     */
    RecurringFrequency: "DAILY" | "WEEKLY" | "MONTHLY" | "YEARLY";
    /** RecurringMaintenanceCreate */
    RecurringMaintenanceCreate: {
      /** Unit Id */
      unit_id: string;
      task_type: components["schemas"]["TaskType"];
      frequency: components["schemas"]["RecurringFrequency"];
      /** Interval Days */
      interval_days?: number | null;
      /**
       * Next Run At
       * Format: date-time
       */
      next_run_at: string;
      /** Description */
      description?: string | null;
    };
    /** RecurringMaintenanceResponse */
    RecurringMaintenanceResponse: {
      /** Id */
      id: string;
      /** Unit Id */
      unit_id: string;
      task_type: components["schemas"]["TaskType"];
      frequency: components["schemas"]["RecurringFrequency"];
      /** Interval Days */
      interval_days?: number | null;
      /**
       * Next Run At
       * Format: date-time
       */
      next_run_at: string;
      /** Is Active */
      is_active: boolean;
      /** Description */
      description?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ReservationCancelRequest */
    ReservationCancelRequest: {
      reason: components["schemas"]["CancellationReason"];
    };
    /** ReservationCreate */
    ReservationCreate: {
      /** Unit Id */
      unit_id: string;
      /**
       * Check In
       * Format: date
       */
      check_in: string;
      /**
       * Check Out
       * Format: date
       */
      check_out: string;
      /**
       * Adults
       * @default 1
       */
      adults?: number;
      /**
       * Children
       * @default 0
       */
      children?: number;
      /**
       * Infants
       * @default 0
       */
      infants?: number;
      payment_method: components["schemas"]["PaymentMethod"];
    };
    /** ReservationListResponse */
    ReservationListResponse: {
      /** Data */
      data: components["schemas"]["ReservationResponse"][];
      pagination: components["schemas"]["PaginationInfo"];
    };
    /** ReservationResponse */
    ReservationResponse: {
      /** Id */
      id: string;
      /** Unit Id */
      unit_id: string;
      /** Guest Id */
      guest_id: string;
      /** Status */
      status: string;
      /**
       * Check In
       * Format: date
       */
      check_in: string;
      /**
       * Check Out
       * Format: date
       */
      check_out: string;
      /** Adults */
      adults: number;
      /** Children */
      children: number;
      /** Infants */
      infants: number;
      /** Total Amount Egp */
      total_amount_egp: number;
      /** Host Amount Egp */
      host_amount_egp: number;
      /** Platform Fee Egp */
      platform_fee_egp: number;
      /** Guest Fee Egp */
      guest_fee_egp: number;
      /** Payment Method */
      payment_method: string;
      /** Checked In At */
      checked_in_at: string | null;
      /** Checked Out At */
      checked_out_at: string | null;
      /** Cancelled At */
      cancelled_at: string | null;
      /** Cancel Reason */
      cancel_reason: string | null;
      /** Refund Amount Egp */
      refund_amount_egp: number | null;
      /**
       * Payment Intents
       * @default []
       */
      payment_intents?: components["schemas"]["PaymentIntentResponse"][];
      /**
       * Promo Applications
       * @default []
       */
      promo_applications?: components["schemas"]["PromoApplicationResponse"][];
      /** Paymob Iframe Url */
      paymob_iframe_url?: string | null;
    };
    /**
     * ReservationStatus
     * @enum {string}
     */
    ReservationStatus: "pending_payment" | "confirmed" | "checked_in" | "checked_out" | "cancelled" | "disputed" | "completed";
    /** RootResponse */
    RootResponse: {
      /** Message */
      message: string;
      /** Version */
      version: string;
    };
    /**
     * StaffRole
     * @enum {string}
     */
    StaffRole: "CLEANER" | "INSPECTOR" | "MAINTENANCE" | "OPERATIONS";
    /** TaskAssignRequest */
    TaskAssignRequest: {
      /** Field Staff Id */
      field_staff_id: string;
    };
    /** TaskAttachmentRequest */
    TaskAttachmentRequest: {
      /** Attachment Url */
      attachment_url: string;
    };
    /** TaskCompleteRequest */
    TaskCompleteRequest: {
      /** Completed At */
      completed_at?: string | null;
      /** Verified By Staff Id */
      verified_by_staff_id?: string | null;
    };
    /** TaskCreate */
    TaskCreate: {
      /** Unit Id */
      unit_id: string;
      task_type: components["schemas"]["TaskType"];
      /** Reservation Id */
      reservation_id?: string | null;
      /** Parent Task Id */
      parent_task_id?: string | null;
      /** @default NORMAL */
      priority?: components["schemas"]["TaskPriority"];
      /**
       * Due By
       * Format: date-time
       */
      due_by: string;
      /** Notes */
      notes?: string | null;
      /** Checklist */
      checklist?: components["schemas"]["ChecklistItem"][] | null;
      /** Created By Id */
      created_by_id?: string | null;
    };
    /** TaskNoteRequest */
    TaskNoteRequest: {
      /** Note */
      note: string;
    };
    /**
     * TaskPriority
     * @enum {string}
     */
    TaskPriority: "LOW" | "NORMAL" | "HIGH" | "URGENT";
    /** TaskResponse */
    TaskResponse: {
      /** Id */
      id: string;
      /** Unit Id */
      unit_id: string;
      /** Reservation Id */
      reservation_id?: string | null;
      /** Parent Task Id */
      parent_task_id?: string | null;
      task_type: components["schemas"]["TaskType"];
      status: components["schemas"]["TaskStatus"];
      priority: components["schemas"]["TaskPriority"];
      /** Field Staff Id */
      field_staff_id?: string | null;
      /**
       * Due By
       * Format: date-time
       */
      due_by: string;
      /** Started At */
      started_at?: string | null;
      /** Completed At */
      completed_at?: string | null;
      /** Verified By Staff Id */
      verified_by_staff_id?: string | null;
      /** Notes */
      notes?: string | null;
      /** Checklist */
      checklist?: components["schemas"]["ChecklistItem"][] | null;
      /** Attachments */
      attachments?: string[] | null;
      /** Created By Id */
      created_by_id?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * TaskStatus
     * @enum {string}
     */
    TaskStatus: "PENDING" | "ASSIGNED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
    /**
     * TaskType
     * @enum {string}
     */
    TaskType: "TURNOVER" | "CLEANING" | "INSPECTION" | "MAINTENANCE";
    /** TaskUpdate */
    TaskUpdate: {
      status?: components["schemas"]["TaskStatus"] | null;
      priority?: components["schemas"]["TaskPriority"] | null;
      /** Field Staff Id */
      field_staff_id?: string | null;
      /** Due By */
      due_by?: string | null;
      /** Notes */
      notes?: string | null;
      /** Checklist */
      checklist?: components["schemas"]["ChecklistItem"][] | null;
      /** Started At */
      started_at?: string | null;
      /** Completed At */
      completed_at?: string | null;
    };
    /** TokenPair */
    TokenPair: {
      /** Access Token */
      access_token: string;
      /** Refresh Token */
      refresh_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type?: string;
      /** Expires In */
      expires_in: number;
    };
    /** TokenRefreshRequest */
    TokenRefreshRequest: {
      /** Refresh Token */
      refresh_token: string;
    };
    /** UserResponse */
    UserResponse: {
      /** Id */
      id: string;
      /** Phone Number */
      phone_number: string | null;
      /** Email */
      email: string | null;
      /** Firebase Uid */
      firebase_uid: string | null;
      /** Display Name */
      display_name: string | null;
      /** Locale */
      locale: string;
      role: components["schemas"]["UserRole"];
      kyc_status: components["schemas"]["KycStatus"];
      /** Is Active */
      is_active: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * UserRole
     * @enum {string}
     */
    UserRole: "guest" | "host" | "field_staff" | "admin";
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** VersionResponse */
    VersionResponse: {
      /** Name */
      name: string;
      /** Version */
      version: string;
      /** Environment */
      environment: string;
    };
    /** WalletResponse */
    WalletResponse: {
      /** Id */
      id: string;
      /** Owner Id */
      owner_id: string | null;
      /** Wallet Type */
      wallet_type: string;
      /** Currency */
      currency: string;
      /** Balance Egp */
      balance_egp: number;
      /** Available Balance Egp */
      available_balance_egp: number;
    };
    /** WebhookResponse */
    WebhookResponse: {
      /**
       * Success
       * @default true
       */
      success?: boolean;
      /**
       * Message
       * @default processed
       */
      message?: string;
    };
    /** AvailabilityResponse */
    app__availability__schemas__AvailabilityResponse: {
      /** Unit Id */
      unit_id: string;
      /**
       * Check In
       * Format: date
       */
      check_in: string;
      /**
       * Check Out
       * Format: date
       */
      check_out: string;
      /** Days */
      days: components["schemas"]["AvailabilityDay"][];
    };
    /** CalendarRuleResponse */
    app__availability__schemas__CalendarRuleResponse: {
      /** Id */
      id: string;
      /** Unit Id */
      unit_id: string;
      /**
       * Date From
       * Format: date
       */
      date_from: string;
      /**
       * Date To
       * Format: date
       */
      date_to: string;
      /** Status */
      status: string;
      /** Block Type */
      block_type: string | null;
      /** Reservation Id */
      reservation_id: string | null;
      /** Price Override */
      price_override: number | null;
    };
    /** AvailabilityResponse */
    app__listings__schemas__AvailabilityResponse: {
      /** Unit Id */
      unit_id: string;
      /**
       * Check In
       * Format: date
       */
      check_in: string;
      /**
       * Check Out
       * Format: date
       */
      check_out: string;
      /** Days */
      days: components["schemas"]["CalendarDay"][];
    };
    /** CalendarRuleResponse */
    app__listings__schemas__CalendarRuleResponse: {
      /** Id */
      id: string;
      /** Unit Id */
      unit_id: string;
      /**
       * Date From
       * Format: date
       */
      date_from: string;
      /**
       * Date To
       * Format: date
       */
      date_to: string;
      /** Status */
      status: string;
      /** Block Type */
      block_type: string | null;
      /** Price Override */
      price_override: number | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Send Otp */
  send_otp_api_v1_auth_otp_send_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["OtpSendRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["OtpSendResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Verify Otp */
  verify_otp_api_v1_auth_otp_verify_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["OtpVerifyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TokenPair"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Firebase Auth */
  firebase_auth_api_v1_auth_firebase_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["FirebaseAuthRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TokenPair"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Refresh Token */
  refresh_token_api_v1_auth_refresh_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenRefreshRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TokenPair"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Logout */
  logout_api_v1_auth_logout_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenRefreshRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Me */
  get_me_api_v1_auth_me_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  /** Get Account */
  get_account_api_v1_auth_me_account_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AccountResponse"];
        };
      };
    };
  };
  /** Update Account */
  update_account_api_v1_auth_me_account_patch: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccountUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AccountResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Register Device Token */
  register_device_token_api_v1_auth_device_token_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeviceTokenRegisterRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DeviceTokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Public Key */
  public_key_api_v1_auth__well_known_jwks_json_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  /** Initiate Kyc */
  initiate_kyc_api_v1_kyc_initiate_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["KycInitiateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["KycInitiateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Submit Kyc */
  submit_kyc_api_v1_kyc_documents__document_id__submit_post: {
    parameters: {
      path: {
        document_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["KycSubmitResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Kyc Status */
  kyc_status_api_v1_kyc_status_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["KycStatusResponse"];
        };
      };
    };
  };
  /** Process Kyc */
  process_kyc_api_v1_kyc_documents__document_id__process_post: {
    parameters: {
      path: {
        document_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["KycDocumentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Listings */
  list_listings_api_v1_listings_get: {
    parameters: {
      query?: {
        q?: string | null;
        sw_lat?: number | null;
        sw_lng?: number | null;
        ne_lat?: number | null;
        ne_lng?: number | null;
        lat?: number | null;
        lng?: number | null;
        radius_km?: number | null;
        check_in?: string | null;
        check_out?: string | null;
        min_price?: number | null;
        max_price?: number | null;
        guests?: number | null;
        cursor?: string | null;
        offset?: number | null;
        limit?: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["Body_list_listings_api_v1_listings_get"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ListingSearchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Post Listing */
  post_listing_api_v1_listings_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ListingCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ListingResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Listing */
  get_listing_api_v1_listings__unit_id__get: {
    parameters: {
      path: {
        unit_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ListingResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Patch Listing */
  patch_listing_api_v1_listings__unit_id__patch: {
    parameters: {
      path: {
        unit_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ListingUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ListingResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Listing Availability */
  get_listing_availability_api_v1_listings__unit_id__availability_get: {
    parameters: {
      query: {
        check_in: string;
        check_out: string;
      };
      path: {
        unit_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["app__listings__schemas__AvailabilityResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Post Publish Listing */
  post_publish_listing_api_v1_listings__unit_id__publish_post: {
    parameters: {
      path: {
        unit_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ListingResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Post Unpublish Listing */
  post_unpublish_listing_api_v1_listings__unit_id__unpublish_post: {
    parameters: {
      path: {
        unit_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ListingResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Post Archive Listing */
  post_archive_listing_api_v1_listings__unit_id__archive_post: {
    parameters: {
      path: {
        unit_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ListingResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Post Host Calendar Rule */
  post_host_calendar_rule_api_v1_listings__unit_id__calendar_post: {
    parameters: {
      path: {
        unit_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CalendarRuleCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["app__listings__schemas__CalendarRuleResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Host Calendar Rule Endpoint */
  delete_host_calendar_rule_endpoint_api_v1_listings__unit_id__calendar__rule_id__delete: {
    parameters: {
      path: {
        unit_id: string;
        rule_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Patch Host Calendar Rule */
  patch_host_calendar_rule_api_v1_listings__unit_id__calendar__rule_id__patch: {
    parameters: {
      path: {
        unit_id: string;
        rule_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CalendarRuleUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["app__listings__schemas__CalendarRuleResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Post Bulk Availability */
  post_bulk_availability_api_v1_listings__unit_id__calendar_bulk_availability_post: {
    parameters: {
      path: {
        unit_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BulkAvailabilityRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["app__listings__schemas__CalendarRuleResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Post Bulk Pricing */
  post_bulk_pricing_api_v1_listings__unit_id__calendar_bulk_pricing_post: {
    parameters: {
      path: {
        unit_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BulkPricingRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["app__listings__schemas__CalendarRuleResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Host Dashboard Endpoint */
  get_host_dashboard_endpoint_api_v1_listings_host_dashboard_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HostDashboardStats"];
        };
      };
    };
  };
  /** Get Host Reservations Endpoint */
  get_host_reservations_endpoint_api_v1_listings_host_reservations_get: {
    parameters: {
      query: {
        check_in: string;
        check_out: string;
        unit_id?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HostReservationCalendarResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Unit Availability */
  get_unit_availability_api_v1_availability__unit_id__get: {
    parameters: {
      query: {
        check_in: string;
        check_out: string;
      };
      path: {
        unit_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["app__availability__schemas__AvailabilityResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Patch Unit Availability */
  patch_unit_availability_api_v1_availability__unit_id__patch: {
    parameters: {
      path: {
        unit_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AvailabilityUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AvailabilityUpdateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Post Task */
  post_task_api_v1_operations_tasks_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Task Endpoint */
  get_task_endpoint_api_v1_operations_tasks__task_id__get: {
    parameters: {
      path: {
        task_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Patch Task */
  patch_task_api_v1_operations_tasks__task_id__patch: {
    parameters: {
      path: {
        task_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Post Assign Task */
  post_assign_task_api_v1_operations_tasks__task_id__assign_post: {
    parameters: {
      path: {
        task_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskAssignRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Post Start Task */
  post_start_task_api_v1_operations_tasks__task_id__start_post: {
    parameters: {
      path: {
        task_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Post Complete Task */
  post_complete_task_api_v1_operations_tasks__task_id__complete_post: {
    parameters: {
      path: {
        task_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskCompleteRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Post Task Note */
  post_task_note_api_v1_operations_tasks__task_id__notes_post: {
    parameters: {
      path: {
        task_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskNoteRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Post Task Attachment */
  post_task_attachment_api_v1_operations_tasks__task_id__attachments_post: {
    parameters: {
      path: {
        task_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskAttachmentRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Task Timeline Endpoint */
  get_task_timeline_endpoint_api_v1_operations_tasks__task_id__timeline_get: {
    parameters: {
      path: {
        task_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
              [key: string]: unknown;
            }[];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Field Staff */
  get_field_staff_api_v1_operations_staff_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FieldStaffResponse"][];
        };
      };
    };
  };
  /** Post Field Staff */
  post_field_staff_api_v1_operations_staff_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["FieldStaffCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FieldStaffResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Maintenance Requests */
  list_maintenance_requests_api_v1_operations_maintenance_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MaintenanceRequestResponse"][];
        };
      };
    };
  };
  /** Post Maintenance Request */
  post_maintenance_request_api_v1_operations_maintenance_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MaintenanceRequestCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MaintenanceRequestResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Maintenance Request Endpoint */
  get_maintenance_request_endpoint_api_v1_operations_maintenance__request_id__get: {
    parameters: {
      path: {
        request_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MaintenanceRequestResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Patch Maintenance Request */
  patch_maintenance_request_api_v1_operations_maintenance__request_id__patch: {
    parameters: {
      path: {
        request_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MaintenanceRequestUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MaintenanceRequestResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Readiness */
  get_readiness_api_v1_operations_readiness__unit_id__get: {
    parameters: {
      query?: {
        reservation_id?: string | null;
      };
      path: {
        unit_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PropertyReadinessResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Patch Readiness */
  patch_readiness_api_v1_operations_readiness__unit_id__patch: {
    parameters: {
      query?: {
        reservation_id?: string | null;
      };
      path: {
        unit_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PropertyReadinessUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PropertyReadinessResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Dashboard */
  get_dashboard_api_v1_operations_dashboard_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["OperationsDashboardResponse"];
        };
      };
    };
  };
  /** Post Recurring Maintenance */
  post_recurring_maintenance_api_v1_operations_recurring_maintenance_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecurringMaintenanceCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RecurringMaintenanceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Reservations */
  get_reservations_api_v1_reservations_get: {
    parameters: {
      query?: {
        status?: components["schemas"]["ReservationStatus"] | null;
        cursor?: string | null;
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ReservationListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Post Reservation */
  post_reservation_api_v1_reservations_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReservationCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ReservationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Reservation Detail */
  get_reservation_detail_api_v1_reservations__reservation_id__get: {
    parameters: {
      path: {
        reservation_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ReservationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Post Confirm Reservation */
  post_confirm_reservation_api_v1_reservations__reservation_id__confirm_post: {
    parameters: {
      path: {
        reservation_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PaymentConfirmationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ReservationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Post Cancel Reservation */
  post_cancel_reservation_api_v1_reservations__reservation_id__cancel_post: {
    parameters: {
      path: {
        reservation_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReservationCancelRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ReservationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Post Check In */
  post_check_in_api_v1_reservations__reservation_id__check_in_post: {
    parameters: {
      path: {
        reservation_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ReservationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Post Check Out */
  post_check_out_api_v1_reservations__reservation_id__check_out_post: {
    parameters: {
      path: {
        reservation_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ReservationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Post Apply Promo */
  post_apply_promo_api_v1_reservations__reservation_id__promo_post: {
    parameters: {
      path: {
        reservation_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PromoApplyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ReservationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Host Bookings */
  get_host_bookings_api_v1_bookings_get: {
    parameters: {
      query?: {
        status?: string | null;
        limit?: number;
        offset?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BookingResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Post Booking */
  post_booking_api_v1_bookings_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["BookingCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BookingResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Booking Detail */
  get_booking_detail_api_v1_bookings__booking_id__get: {
    parameters: {
      path: {
        booking_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BookingResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Patch Booking */
  patch_booking_api_v1_bookings__booking_id__patch: {
    parameters: {
      path: {
        booking_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BookingUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BookingResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get My Wallet */
  get_my_wallet_api_v1_finance_wallets_me_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["WalletResponse"];
        };
      };
    };
  };
  /** List Wallet Ledger */
  list_wallet_ledger_api_v1_finance_wallets__wallet_id__ledger_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      path: {
        wallet_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LedgerListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Escrows */
  list_escrows_api_v1_finance_escrow_get: {
    parameters: {
      query?: {
        host_id?: string | null;
        status?: string | null;
        limit?: number;
        offset?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["EscrowListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Escrow */
  get_escrow_api_v1_finance_escrow__escrow_id__get: {
    parameters: {
      path: {
        escrow_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Release Escrow Endpoint */
  release_escrow_endpoint_api_v1_finance_escrow__escrow_id__release_post: {
    parameters: {
      path: {
        escrow_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Hold Escrow Endpoint */
  hold_escrow_endpoint_api_v1_finance_escrow__escrow_id__hold_post: {
    parameters: {
      query?: {
        hold_hours?: number;
      };
      path: {
        escrow_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Payouts */
  list_payouts_api_v1_finance_payouts_get: {
    parameters: {
      query?: {
        status?: string | null;
        limit?: number;
        offset?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PayoutListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Payout Request */
  create_payout_request_api_v1_finance_payouts_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PayoutRequestCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PayoutRequestResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Process Payout Endpoint */
  process_payout_endpoint_api_v1_finance_payouts__payout_id__process_post: {
    parameters: {
      path: {
        payout_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PayoutProcessRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PayoutRequestResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Paymob Webhook */
  paymob_webhook_api_v1_finance_webhooks_paymob_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["WebhookResponse"];
        };
      };
    };
  };
  /** Stripe Webhook */
  stripe_webhook_api_v1_finance_webhooks_stripe_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["WebhookResponse"];
        };
      };
    };
  };
  /** Health Check */
  health_check_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  /** Liveness Check */
  liveness_check_health_live_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  /** Readiness Check */
  readiness_check_health_ready_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  /** Deep Health Check */
  deep_health_check_health_deep_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  /** Metrics */
  metrics_metrics_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "text/plain": string;
        };
      };
    };
  };
  /** Version */
  version_version_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["VersionResponse"];
        };
      };
    };
  };
  /** Root */
  root__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RootResponse"];
        };
      };
    };
  };
}
