/**
 * Localized admin report names — mirrors web messages adminReports.*
 * (EN/AR parity with apps/web/messages).
 */

export const REPORT_CATEGORIES: Record<string, { en: string; ar: string }> = {
  overview: { en: "Overview", ar: "نظرة عامة" },
  users: { en: "Users", ar: "المستخدمون" },
  listings: { en: "Listings", ar: "الإعلانات" },
  bookings: { en: "Bookings", ar: "الحجوزات" },
  financial: { en: "Financial", ar: "الشؤون المالية" },
  payments: { en: "Payments", ar: "المدفوعات" },
  payouts: { en: "Payouts", ar: "الدفعات" },
  operations: { en: "Operations", ar: "العمليات" },
  trust: { en: "Trust & KYC", ar: "الثقة والتحقق" },
  disputes: { en: "Disputes", ar: "النزاعات" },
  reviews: { en: "Reviews", ar: "التقييمات" },
  users_trust: { en: "Users & Trust", ar: "المستخدمون والثقة" },
};

export const REPORT_REPORTS: Record<string, { en: string; ar: string }> = {
  marketplace_overview: { en: "Marketplace Overview", ar: "نظرة عامة على السوق" },
  booking_summary: { en: "Booking Summary", ar: "ملخص الحجوزات" },
  revenue_summary: { en: "Revenue Summary", ar: "ملخص الإيرادات" },
  payment_summary: { en: "Payment Summary", ar: "ملخص المدفوعات" },
  payout_summary: { en: "Payout Summary", ar: "ملخص الدفعات" },
  users: { en: "User Report", ar: "تقرير المستخدمين" },
  guests: { en: "Guest Report", ar: "تقرير الضيوف" },
  hosts: { en: "Host Report", ar: "تقرير المضيفين" },
  kyc_status: { en: "KYC Status Report", ar: "تقرير حالة التحقق" },
  listing_inventory: { en: "Listing Inventory", ar: "مخزون الإعلانات" },
  listing_status: { en: "Listing Status", ar: "حالة الإعلانات" },
  supply_by_governorate: { en: "Supply by Governorate", ar: "المعروض حسب المحافظة" },
  supply_by_city: { en: "Supply by City", ar: "المعروض حسب المدينة" },
  listing_activity: { en: "Listing Activity", ar: "نشاط الإعلانات" },
  bookings: { en: "Booking Report", ar: "تقرير الحجوزات" },
  booking_status: { en: "Booking Status", ar: "حالة الحجوزات" },
  completed_bookings: { en: "Completed Bookings", ar: "الحجوزات المكتملة" },
  cancelled_bookings: { en: "Cancelled Bookings", ar: "الحجوزات الملغاة" },
  rebooked_bookings: { en: "Rebooked Bookings", ar: "الحجوزات المعاد حجزها" },
  booking_financials: { en: "Booking Financials", ar: "البيانات المالية للحجوزات" },
  stayos_revenue: { en: "StayOS Revenue", ar: "إيرادات StayOS" },
  host_commission: { en: "Host Commission", ar: "عمولة المضيف" },
  guest_commission: { en: "Guest Commission", ar: "عمولة الضيف" },
  host_earnings: { en: "Host Earnings", ar: "أرباح المضيفين" },
  guest_payments: { en: "Guest Payments", ar: "مدفوعات الضيوف" },
  refunds: { en: "Refunds", ar: "المبالغ المستردة" },
  commercial_adjustments: { en: "Commercial Adjustments", ar: "التعديلات التجارية" },
  payment_transactions: { en: "Payment Transactions", ar: "معاملات الدفع" },
  payment_status: { en: "Payment Status", ar: "حالة الدفع" },
  failed_payments: { en: "Failed Payments", ar: "المدفوعات الفاشلة" },
  refund_transactions: { en: "Refund Transactions", ar: "معاملات الاسترداد" },
  payouts: { en: "Host Payouts", ar: "دفعات المضيفين" },
  pending_payouts: { en: "Pending Payouts", ar: "الدفعات المعلقة" },
  paid_payouts: { en: "Paid Payouts", ar: "الدفعات المدفوعة" },
  failed_payouts: { en: "Failed Payouts", ar: "الدفعات الفاشلة" },
  operational_bookings: { en: "Operational Bookings", ar: "الحجوزات التشغيلية" },
  check_in: { en: "Check-in Report", ar: "تقرير تسجيل الوصول" },
  check_out: { en: "Check-out Report", ar: "تقرير تسجيل المغادرة" },
  operational_exceptions: { en: "Operational Exceptions", ar: "الاستثناءات التشغيلية" },
  automated_verification: { en: "Automated Verification", ar: "التحقق الآلي" },
  manual_review_cases: { en: "Manual Review Cases", ar: "حالات المراجعة اليدوية" },
  disputes: { en: "Disputes", ar: "النزاعات" },
  dispute_resolution: { en: "Resolution Status", ar: "حالة الحل" },
  reviews: { en: "Reviews", ar: "التقييمات" },
  ratings: { en: "Ratings", ar: "التصنيفات" },
  moderation_status: { en: "Moderation Status", ar: "حالة الإشراف" },
  booking_economics_summary: { en: "Booking Economics Summary", ar: "ملخص اقتصاديات الحجوزات" },
  vat_payable: { en: "VAT Payable", ar: "ضريبة القيمة المضافة المستحقة" },
  vat_calculated: { en: "VAT Calculated", ar: "ضريبة القيمة المضافة المحسوبة" },
};

export const REPORT_DATEBASIS: Record<string, { en: string; ar: string }> = {
  snapshot: { en: "Snapshot (as of now)", ar: "لقطة لحظية (الآن)" },
  booking_created: { en: "Booking creation date", ar: "تاريخ إنشاء الحجز" },
  payment_created: { en: "Payment created date", ar: "تاريخ إنشاء الدفعة" },
  payout_requested: { en: "Payout request date", ar: "تاريخ طلب الدفعة" },
  payout_processed: { en: "Payout processed date", ar: "تاريخ تنفيذ الدفعة" },
  user_created: { en: "Account creation date", ar: "تاريخ إنشاء الحساب" },
  listing_created: { en: "Listing creation date", ar: "تاريخ إنشاء الإعلان" },
  dispute_created: { en: "Dispute opened date", ar: "تاريخ فتح النزاع" },
  review_created: { en: "Review submitted date", ar: "تاريخ إرسال التقييم" },
  report_created: { en: "Report created date", ar: "تاريخ إنشاء البلاغ" },
  document_created: { en: "Document uploaded date", ar: "تاريخ رفع المستند" },
  adjustment_created: { en: "Adjustment date", ar: "تاريخ التعديل" },
  transaction_created: { en: "Transaction date", ar: "تاريخ المعاملة" },
  ledger_recognised: { en: "Ledger recognition date", ar: "تاريخ الاعتراف في القيود" },
  check_in_date: { en: "Check-in date", ar: "تاريخ تسجيل الوصول" },
  check_out_date: { en: "Check-out date", ar: "تاريخ تسجيل المغادرة" },
};

export const REPORT_REASONS: Record<string, { en: string; ar: string }> = {
  no_rebooking_linkage: { en: "Booking rebooking linkage is not yet modelled — bookings have no replaced_by/rebooked_from field.", ar: "ربط الحجوزات المعاد حجزها غير موجود في النموذج بعد — لا توجد حقول replaced_by/rebooked_from في الحجز." },
};

