/**
 * Localized admin report names — mirrors web messages adminReports.*
 * (EN/AR parity with apps/web/messages).
 */

export const REPORT_CATEGORIES: Record<string, { en: string; ar: string }> = {
  overview: { en: "Overview", ar: "نظرة عامة" },
  users: { en: "Users", ar: "المستخدمون" },
  listings: { en: "Listings", ar: "الإعلانات" },
  bookings: { en: "Bookings", ar: "الحجوزات" },
  financial: { en: "Financial", ar: "الشؤون المالية" },
  payments: { en: "Payments", ar: "المدفوعات" },
  payouts: { en: "Payouts", ar: "الدفعات" },
  operations: { en: "Operations", ar: "العمليات" },
  trust: { en: "Trust & KYC", ar: "الثقة والتحقق" },
  disputes: { en: "Disputes", ar: "النزاعات" },
  reviews: { en: "Reviews", ar: "التقييمات" },
  users_trust: { en: "Users & Trust", ar: "المستخدمون والثقة" },
};

export const REPORT_REPORTS: Record<string, { en: string; ar: string }> = {
  marketplace_overview: { en: "Marketplace Overview", ar: "نظرة عامة على السوق" },
  booking_summary: { en: "Booking Summary", ar: "ملخص الحجوزات" },
  revenue_summary: { en: "Revenue Summary", ar: "ملخص الإيرادات" },
  payment_summary: { en: "Payment Summary", ar: "ملخص المدفوعات" },
  payout_summary: { en: "Payout Summary", ar: "ملخص الدفعات" },
  users: { en: "User Report", ar: "تقرير المستخدمين" },
  guests: { en: "Guest Report", ar: "تقرير الضيوف" },
  hosts: { en: "Host Report", ar: "تقرير المضيفين" },
  kyc_status: { en: "KYC Status Report", ar: "تقرير حالة التحقق" },
  listing_inventory: { en: "Listing Inventory", ar: "مخزون الإعلانات" },
  listing_status: { en: "Listing Status", ar: "حالة الإعلانات" },
  supply_by_governorate: { en: "Supply by Governorate", ar: "المعروض حسب المحافظة" },
  supply_by_city: { en: "Supply by City", ar: "المعروض حسب المدينة" },
  listing_activity: { en: "Listing Activity", ar: "نشاط الإعلانات" },
  bookings: { en: "Booking Report", ar: "تقرير الحجوزات" },
  booking_status: { en: "Booking Status", ar: "حالة الحجوزات" },
  completed_bookings: { en: "Completed Bookings", ar: "الحجوزات المكتملة" },
  cancelled_bookings: { en: "Cancelled Bookings", ar: "الحجوزات الملغاة" },
  rebooked_bookings: { en: "Rebooked Bookings", ar: "الحجوزات المعاد حجزها" },
  booking_financials: { en: "Booking Financials", ar: "البيانات المالية للحجوزات" },
  stayos_revenue: { en: "StayOS Revenue", ar: "إيرادات StayOS" },
  host_commission: { en: "Host Commission", ar: "عمولة المضيف" },
  guest_commission: { en: "Guest Commission", ar: "عمولة الضيف" },
  host_earnings: { en: "Host Earnings", ar: "أرباح المضيفين" },
  guest_payments: { en: "Guest Payments", ar: "مدفوعات الضيوف" },
  refunds: { en: "Refunds", ar: "المبالغ المستردة" },
  commercial_adjustments: { en: "Commercial Adjustments", ar: "التعديلات التجارية" },
  payment_transactions: { en: "Payment Transactions", ar: "معاملات الدفع" },
  payment_status: { en: "Payment Status", ar: "حالة الدفع" },
  failed_payments: { en: "Failed Payments", ar: "المدفوعات الفاشلة" },
  refund_transactions: { en: "Refund Transactions", ar: "معاملات الاسترداد" },
  payouts: { en: "Host Payouts", ar: "دفعات المضيفين" },
  pending_payouts: { en: "Pending Payouts", ar: "الدفعات المعلقة" },
  paid_payouts: { en: "Paid Payouts", ar: "الدفعات المدفوعة" },
  failed_payouts: { en: "Failed Payouts", ar: "الدفعات الفاشلة" },
  operational_bookings: { en: "Operational Bookings", ar: "الحجوزات التشغيلية" },
  check_in: { en: "Check-in Report", ar: "تقرير تسجيل الوصول" },
  check_out: { en: "Check-out Report", ar: "تقرير تسجيل المغادرة" },
  operational_exceptions: { en: "Operational Exceptions", ar: "الاستثناءات التشغيلية" },
  automated_verification: { en: "Automated Verification", ar: "التحقق الآلي" },
  manual_review_cases: { en: "Manual Review Cases", ar: "حالات المراجعة اليدوية" },
  disputes: { en: "Disputes", ar: "النزاعات" },
  dispute_resolution: { en: "Resolution Status", ar: "حالة الحل" },
  reviews: { en: "Reviews", ar: "التقييمات" },
  ratings: { en: "Ratings", ar: "التصنيفات" },
  moderation_status: { en: "Moderation Status", ar: "حالة الإشراف" },
  booking_economics_summary: { en: "Booking Economics Summary", ar: "ملخص اقتصاديات الحجوزات" },
  vat_payable: { en: "VAT Payable", ar: "ضريبة القيمة المضافة المستحقة" },
  vat_calculated: { en: "VAT Calculated", ar: "ضريبة القيمة المضافة المحسوبة" },
};

export const REPORT_DATEBASIS: Record<string, { en: string; ar: string }> = {
  snapshot: { en: "Snapshot (as of now)", ar: "لقطة لحظية (الآن)" },
  booking_created: { en: "Booking creation date", ar: "تاريخ إنشاء الحجز" },
  payment_created: { en: "Payment created date", ar: "تاريخ إنشاء الدفعة" },
  payout_requested: { en: "Payout request date", ar: "تاريخ طلب الدفعة" },
  payout_processed: { en: "Payout processed date", ar: "تاريخ تنفيذ الدفعة" },
  user_created: { en: "Account creation date", ar: "تاريخ إنشاء الحساب" },
  listing_created: { en: "Listing creation date", ar: "تاريخ إنشاء الإعلان" },
  dispute_created: { en: "Dispute opened date", ar: "تاريخ فتح النزاع" },
  review_created: { en: "Review submitted date", ar: "تاريخ إرسال التقييم" },
  report_created: { en: "Report created date", ar: "تاريخ إنشاء البلاغ" },
  document_created: { en: "Document uploaded date", ar: "تاريخ رفع المستند" },
  adjustment_created: { en: "Adjustment date", ar: "تاريخ التعديل" },
  transaction_created: { en: "Transaction date", ar: "تاريخ المعاملة" },
  ledger_recognised: { en: "Ledger recognition date", ar: "تاريخ الاعتراف في القيود" },
  check_in_date: { en: "Check-in date", ar: "تاريخ تسجيل الوصول" },
  check_out_date: { en: "Check-out date", ar: "تاريخ تسجيل المغادرة" },
};

export const REPORT_REASONS: Record<string, { en: string; ar: string }> = {
  no_rebooking_linkage: { en: "Booking rebooking linkage is not yet modelled — bookings have no replaced_by/rebooked_from field.", ar: "ربط الحجوزات المعاد حجزها غير موجود في النموذج بعد — لا توجد حقول replaced_by/rebooked_from في الحجز." },
};

export const REPORT_COLUMNS: Record<string, { en: string; ar: string }> = {
  accommodation_egp: { en: 'Accommodation (EGP)', ar: 'الإقامة (ج.م)' },
  adjustment_amount_egp: { en: 'Adjustment (EGP)', ar: 'التعديل (ج.م)' },
  adjustment_id: { en: 'Adjustment', ar: 'التعديل' },
  adjustment_type: { en: 'Adjustment Type', ar: 'نوع التعديل' },
  amount_egp: { en: 'Amount (EGP)', ar: 'المبلغ (ج.م)' },
  avg_rating: { en: 'Avg Rating', ar: 'متوسط التقييم' },
  base_price_egp: { en: 'Base Price (EGP)', ar: 'السعر الأساسي (ج.م)' },
  booking_id: { en: 'Booking', ar: 'الحجز' },
  bookings: { en: 'Bookings', ar: 'الحجوزات' },
  bookings_count: { en: 'Bookings', ar: 'الحجوزات' },
  cancel_reason: { en: 'Cancel Reason', ar: 'سبب الإلغاء' },
  cancelled_at: { en: 'Cancelled', ar: 'تاريخ الإلغاء' },
  category: { en: 'Category', ar: 'الفئة' },
  check_in: { en: 'Check-in', ar: 'تسجيل الوصول' },
  check_out: { en: 'Check-out', ar: 'تسجيل المغادرة' },
  checked_in_at: { en: 'Checked In', ar: 'تم تسجيل الوصول' },
  checked_out_at: { en: 'Checked Out', ar: 'تم تسجيل المغادرة' },
  city: { en: 'City', ar: 'المدينة' },
  collected_egp: { en: 'Collected (EGP)', ar: 'المحصّل (ج.م)' },
  count: { en: 'Count', ar: 'العدد' },
  created_at: { en: 'Created', ar: 'تاريخ الإنشاء' },
  credit_egp: { en: 'Credit (EGP)', ar: 'دائن (ج.م)' },
  debit_egp: { en: 'Debit (EGP)', ar: 'مدين (ج.م)' },
  display_name: { en: 'Name', ar: 'الاسم' },
  dispute_id: { en: 'Dispute', ar: 'النزاع' },
  document_id: { en: 'Document', ar: 'المستند' },
  document_type: { en: 'Doc Type', ar: 'نوع المستند' },
  entry_type: { en: 'Type', ar: 'النوع' },
  exception: { en: 'Exception', ar: 'الاستثناء' },
  expected_payout_at: { en: 'Expected Payout', ar: 'الدفعة المتوقعة' },
  failure_reason: { en: 'Failure Reason', ar: 'سبب الفشل' },
  funds_status: { en: 'Funds', ar: 'الأموال' },
  governorate: { en: 'Governorate', ar: 'المحافظة' },
  guest_commission_egp: { en: 'Guest Commission (EGP)', ar: 'عمولة الضيف (ج.م)' },
  guest_name: { en: 'Guest', ar: 'الضيف' },
  guest_total_egp: { en: 'Guest Total (EGP)', ar: 'إجمالي الضيف (ج.م)' },
  guests: { en: 'Guests', ar: 'الضيوف' },
  host_commission_egp: { en: 'Host Commission (EGP)', ar: 'عمولة المضيف (ج.م)' },
  host_id: { en: 'Host ID', ar: 'معرّف المضيف' },
  host_name: { en: 'Host', ar: 'المضيف' },
  host_net_egp: { en: 'Host Net (EGP)', ar: 'صافي المضيف (ج.م)' },
  host_payable_egp: { en: 'Host Payable (EGP)', ar: 'مستحق للمضيف (ج.م)' },
  is_active: { en: 'Active', ar: 'نشط' },
  is_hidden: { en: 'Hidden', ar: 'مخفي' },
  kyc_status: { en: 'KYC', ar: 'التحقق' },
  listing_title: { en: 'Listing', ar: 'الإعلان' },
  listings_count: { en: 'Listings', ar: 'الإعلانات' },
  metric: { en: 'Metric', ar: 'المقياس' },
  month: { en: 'Month', ar: 'الشهر' },
  net_activity_egp: { en: 'Net Activity (EGP)', ar: 'صافي النشاط (ج.م)' },
  nights: { en: 'Nights', ar: 'الليالي' },
  payment_collected_egp: { en: 'Collected (EGP)', ar: 'المحصّل (ج.م)' },
  payment_id: { en: 'Payment', ar: 'الدفعة' },
  payment_method: { en: 'Method', ar: 'طريقة الدفع' },
  payment_status: { en: 'Payment', ar: 'الدفع' },
  payout_id: { en: 'Payout', ar: 'الدفعة' },
  payout_status: { en: 'Payout', ar: 'الدفعة' },
  processed_at: { en: 'Processed', ar: 'تاريخ المعالجة' },
  property_type: { en: 'Property Type', ar: 'نوع العقار' },
  provider: { en: 'Provider', ar: 'المزوّد' },
  published_at: { en: 'Published', ar: 'تاريخ النشر' },
  rating: { en: 'Rating', ar: 'التقييم' },
  reason: { en: 'Reason', ar: 'السبب' },
  refund_amount_egp: { en: 'Refund (EGP)', ar: 'المسترد (ج.م)' },
  refunded_at: { en: 'Refunded', ar: 'تاريخ الاسترداد' },
  refunded_egp: { en: 'Refunded (EGP)', ar: 'المسترد (ج.م)' },
  reject_reason: { en: 'Reject Reason', ar: 'سبب الرفض' },
  report_id: { en: 'Report', ar: 'البلاغ' },
  resolved_at: { en: 'Resolved', ar: 'تاريخ الحل' },
  review_id: { en: 'Review', ar: 'التقييم' },
  reviewer_role: { en: 'Reviewer', ar: 'المراجع' },
  reviews_count: { en: 'Reviews', ar: 'التقييمات' },
  role: { en: 'Role', ar: 'الدور' },
  status: { en: 'Status', ar: 'الحالة' },
  stay_phase: { en: 'Stay Phase', ar: 'مرحلة الإقامة' },
  stayos_revenue_egp: { en: 'StayOS Revenue (EGP)', ar: 'إيرادات StayOS (ج.م)' },
  taxable_amount_egp: { en: 'Taxable (EGP)', ar: 'الخاضع للضريبة (ج.م)' },
  transaction_id: { en: 'Transaction', ar: 'المعاملة' },
  transaction_type: { en: 'Type', ar: 'النوع' },
  unit_id: { en: 'Unit', ar: 'الوحدة' },
  updated_at: { en: 'Updated', ar: 'تاريخ التحديث' },
  user_id: { en: 'User', ar: 'المستخدم' },
  user_name: { en: 'User', ar: 'المستخدم' },
  value: { en: 'Value', ar: 'القيمة' },
  vat_calculated_egp: { en: 'VAT Calculated (EGP)', ar: 'ض.ق.م محسوبة (ج.م)' },
  vat_egp: { en: 'VAT Calculated (EGP)', ar: 'ض.ق.م محسوبة (ج.م)' },
  vat_held_egp: { en: 'VAT Held (EGP)', ar: 'ض.ق.م محتجزة (ج.م)' },
  vat_payable_egp: { en: 'VAT Payable (EGP)', ar: 'ض.ق.م مستحقة (ج.م)' },
  vat_recognised_egp: { en: 'VAT Recognised (EGP)', ar: 'ض.ق.م معترف بها (ج.م)' },
  vat_reversed_egp: { en: 'VAT Reversed (EGP)', ar: 'ض.ق.م معكوسة (ج.م)' },
  verified_at: { en: 'Verified', ar: 'تاريخ التحقق' },
};