"""Admin Reports catalog — the single registry of reportable datasets.

Every entry declares: the category (catalog grouping), the columns the
builder returns (frontend translates ``adminReports.columns.<key>``),
which of the shared filter params the report honours, which columns are
server-sortable, which money columns roll into the totals row, and the
canonical ``date_basis`` (reported to the UI so date filters are never
ambiguous). ``implemented=False`` entries appear in the catalog disabled
with a reason — no fake reports.
"""

from dataclasses import dataclass, field


@dataclass(frozen=True)
class ReportDef:
    key: str
    category: str
    builder: str
    columns: tuple[str, ...]
    date_basis: str
    filters: tuple[str, ...] = ()
    sortable: tuple[str, ...] = ()
    default_sort: str = "created_at"
    money_columns: tuple[str, ...] = ()
    implemented: bool = True
    unavailable_reason: str | None = None
    fixed: dict = field(default_factory=dict)
    # i18n keys under ``adminReports.notes.*`` — semantic disclaimer shown
    # under the report title (e.g. "booking economics ≠ collected revenue").
    note: str | None = None
    # money_column → i18n key under ``adminReports.totals.*``; overrides
    # the column label so totals say what they actually sum (e.g.
    # "gross credits" / "net recognised").
    total_labels: dict = field(default_factory=dict)


_COMMON = ("date_from", "date_to")
_BOOKING_FILTERS = _COMMON + (
    "status",
    "host_id",
    "guest_id",
    "unit_id",
    "governorate",
    "city",
)
_FIN_FILTERS = _BOOKING_FILTERS + (
    "payment_status",
    "payout_status",
    "min_amount",
    "max_amount",
)

_BOOKING_COLS = (
    "booking_id",
    "created_at",
    "check_in",
    "check_out",
    "status",
    "stay_phase",
    "guest_name",
    "host_name",
    "listing_title",
    "governorate",
    "city",
    "nights",
    "guests",
)

_FINANCIAL_COLS = _BOOKING_COLS + (
    "accommodation_egp",
    "cleaning_fee_egp",
    "host_commission_egp",
    "guest_commission_egp",
    "taxable_amount_egp",
    "vat_egp",
    "guest_total_egp",
    "host_net_egp",
    "stayos_revenue_egp",
    "payment_status",
    "payment_collected_egp",
    "refund_amount_egp",
    "funds_status",
    "payout_status",
    "expected_payout_at",
    "adjustment_amount_egp",
)

CATALOG: tuple[ReportDef, ...] = (
    # ---- A. Overview ----------------------------------------------------
    ReportDef(
        "marketplace_overview",
        "overview",
        "marketplace_overview",
        ("metric", "value"),
        date_basis="snapshot",
    ),
    ReportDef(
        "booking_summary",
        "overview",
        "grouped_booking_status",
        ("status", "count"),
        date_basis="booking_created",
        filters=_COMMON,
    ),
    ReportDef(
        "revenue_summary",
        "overview",
        "recognition_by_month",
        (
            "month",
            "stayos_revenue_egp",
            "vat_payable_egp",
            "host_payable_egp",
            "collected_egp",
            "refunded_egp",
            "net_activity_egp",
            "bookings_count",
        ),
        date_basis="ledger_recognised",
        filters=_COMMON,
        note="recognition_semantics",
        money_columns=(
            "stayos_revenue_egp",
            "vat_payable_egp",
            "host_payable_egp",
            "collected_egp",
            "refunded_egp",
            "net_activity_egp",
            "bookings_count",
        ),
        total_labels={
            "stayos_revenue_egp": "net_recognised_revenue",
            "vat_payable_egp": "vat_payable",
            "host_payable_egp": "host_payable",
            "collected_egp": "collected",
            "refunded_egp": "refunded",
            "net_activity_egp": "net_activity",
            "bookings_count": "recognised_bookings",
        },
    ),
    ReportDef(
        "payment_summary",
        "overview",
        "payments_grouped",
        ("payment_status", "payment_method", "count", "amount_egp", "refund_amount_egp"),
        date_basis="payment_created",
        filters=_COMMON + ("status",),
        money_columns=("count", "amount_egp", "refund_amount_egp"),
    ),
    ReportDef(
        "payout_summary",
        "overview",
        "payouts_grouped",
        ("payout_status", "count", "amount_egp"),
        date_basis="payout_requested",
        filters=_COMMON,
        money_columns=("count", "amount_egp"),
    ),
    # ---- B. Users & Trust -------------------------------------------------
    ReportDef(
        "users",
        "users_trust",
        "users_list",
        ("user_id", "display_name", "role", "kyc_status", "is_active", "created_at"),
        date_basis="user_created",
        filters=_COMMON + ("role", "kyc_status"),
        sortable=("created_at", "display_name"),
    ),
    ReportDef(
        "guests",
        "users_trust",
        "users_list",
        ("user_id", "display_name", "kyc_status", "is_active", "created_at", "bookings_count"),
        date_basis="user_created",
        filters=_COMMON + ("kyc_status",),
        sortable=("created_at", "display_name"),
        fixed={"role": "guest"},
    ),
    ReportDef(
        "hosts",
        "users_trust",
        "users_list",
        ("user_id", "display_name", "kyc_status", "is_active", "created_at", "listings_count"),
        date_basis="user_created",
        filters=_COMMON + ("kyc_status",),
        sortable=("created_at", "display_name"),
        fixed={"role": "host"},
    ),
    ReportDef(
        "kyc_status",
        "users_trust",
        "kyc_grouped",
        ("kyc_status", "count"),
        date_basis="snapshot",
    ),
    # ---- C. Listings -----------------------------------------------------
    ReportDef(
        "listing_inventory",
        "listings",
        "listings_list",
        (
            "unit_id",
            "listing_title",
            "host_name",
            "status",
            "property_type",
            "governorate",
            "city",
            "base_price_egp",
            "created_at",
        ),
        date_basis="listing_created",
        filters=_COMMON + ("status", "host_id", "governorate", "city", "property_type"),
        sortable=("created_at", "base_price_egp"),
        money_columns=("base_price_egp",),
    ),
    ReportDef(
        "listing_status",
        "listings",
        "listings_grouped_status",
        ("status", "count"),
        date_basis="snapshot",
        filters=_COMMON,
    ),
    ReportDef(
        "supply_by_governorate",
        "listings",
        "supply_grouped",
        ("governorate", "count"),
        date_basis="snapshot",
        filters=("status",),
        fixed={"group_by": "governorate"},
    ),
    ReportDef(
        "supply_by_city",
        "listings",
        "supply_grouped",
        ("governorate", "city", "count"),
        date_basis="snapshot",
        filters=("status", "governorate"),
        fixed={"group_by": "city"},
    ),
    ReportDef(
        "listing_activity",
        "listings",
        "listings_by_month",
        ("month", "count"),
        date_basis="listing_created",
        filters=_COMMON,
    ),
    # ---- D. Bookings -----------------------------------------------------
    ReportDef(
        "bookings",
        "bookings",
        "bookings_list",
        _BOOKING_COLS,
        date_basis="booking_created",
        filters=_BOOKING_FILTERS + ("stay_in_range",),
        sortable=("created_at", "check_in", "check_out"),
    ),
    ReportDef(
        "booking_status",
        "bookings",
        "grouped_booking_status",
        ("status", "count"),
        date_basis="booking_created",
        filters=_COMMON,
    ),
    ReportDef(
        "completed_bookings",
        "bookings",
        "bookings_list",
        _BOOKING_COLS,
        date_basis="booking_created",
        filters=_BOOKING_FILTERS,
        sortable=("created_at", "check_in", "check_out"),
        fixed={"status": "completed"},
    ),
    ReportDef(
        "cancelled_bookings",
        "bookings",
        "bookings_list",
        _BOOKING_COLS + ("cancel_reason", "cancelled_at"),
        date_basis="booking_created",
        filters=_BOOKING_FILTERS + ("cancel_reason",),
        sortable=("created_at", "cancelled_at"),
        fixed={"status": "cancelled"},
    ),
    ReportDef(
        "rebooked_bookings",
        "bookings",
        "bookings_list",
        _BOOKING_COLS,
        date_basis="booking_created",
        implemented=False,
        unavailable_reason="no_rebooking_linkage",
    ),
    ReportDef(
        "booking_financials",
        "bookings",
        "booking_financials",
        _FINANCIAL_COLS,
        date_basis="booking_created",
        filters=_FIN_FILTERS,
        sortable=("created_at", "check_in"),
        # Totals here are *gross booking economics* for the selected set —
        # unpaid/cancelled/future bookings included; not collected revenue.
        note="economics_not_revenue",
        money_columns=(
            "accommodation_egp",
            "cleaning_fee_egp",
            "host_commission_egp",
            "guest_commission_egp",
            "taxable_amount_egp",
            "vat_egp",
            "guest_total_egp",
            "host_net_egp",
            "stayos_revenue_egp",
            "payment_collected_egp",
            "refund_amount_egp",
            "adjustment_amount_egp",
        ),
        total_labels={
            "vat_egp": "vat_calculated",
            "guest_total_egp": "gross_booking_value",
            "host_net_egp": "host_net",
            "stayos_revenue_egp": "stayos_economics",
            "payment_collected_egp": "collected",
            "refund_amount_egp": "refunded",
        },
    ),
    ReportDef(
        "booking_economics_summary",
        "bookings",
        "economics_by_month",
        (
            "month",
            "bookings_count",
            "accommodation_egp",
            "cleaning_fee_egp",
            "host_commission_egp",
            "guest_commission_egp",
            "taxable_amount_egp",
            "vat_calculated_egp",
            "guest_total_egp",
            "host_net_egp",
            "stayos_revenue_egp",
        ),
        date_basis="booking_created",
        filters=_BOOKING_FILTERS,
        note="economics_not_revenue",
        money_columns=(
            "bookings_count",
            "accommodation_egp",
            "cleaning_fee_egp",
            "host_commission_egp",
            "guest_commission_egp",
            "taxable_amount_egp",
            "vat_calculated_egp",
            "guest_total_egp",
            "host_net_egp",
            "stayos_revenue_egp",
        ),
        total_labels={
            "bookings_count": "bookings_in_period",
            "vat_calculated_egp": "vat_calculated",
            "guest_total_egp": "gross_booking_value",
            "host_net_egp": "host_net",
            "stayos_revenue_egp": "stayos_economics",
        },
    ),
    # ---- E. Financial ----------------------------------------------------
    ReportDef(
        "stayos_revenue",
        "financial",
        "ledger_account_report",
        ("created_at", "booking_id", "entry_type", "amount_egp", "transaction_type"),
        date_basis="ledger_recognised",
        filters=_COMMON + ("entry_type",),
        sortable=("created_at", "amount_egp"),
        note="signed_ledger",
        # credit_egp/debit_egp are row-level helper keys (not displayed
        # columns) so totals expose gross credits, gross debits and the
        # signed net — debits subtract, they do not add.
        money_columns=("credit_egp", "debit_egp", "amount_egp"),
        total_labels={
            "credit_egp": "gross_credits",
            "debit_egp": "gross_debits",
            "amount_egp": "net_recognised_revenue",
        },
        fixed={"ledger_account": "platform_revenue"},
    ),
    ReportDef(
        "host_commission",
        "financial",
        "booking_financials",
        _BOOKING_COLS + ("accommodation_egp", "host_commission_egp", "host_net_egp"),
        date_basis="booking_created",
        filters=_FIN_FILTERS,
        note="economics_not_revenue",
        money_columns=("accommodation_egp", "host_commission_egp", "host_net_egp"),
        total_labels={"host_net_egp": "host_net"},
        fixed={"share": "host"},
    ),
    ReportDef(
        "guest_commission",
        "financial",
        "booking_financials",
        _BOOKING_COLS + ("accommodation_egp", "guest_commission_egp", "guest_total_egp"),
        date_basis="booking_created",
        filters=_FIN_FILTERS,
        note="economics_not_revenue",
        money_columns=("accommodation_egp", "guest_commission_egp", "guest_total_egp"),
        fixed={"share": "guest"},
    ),
    ReportDef(
        "vat_payable",
        "financial",
        "vat_by_booking",
        _BOOKING_COLS[:1]
        + ("created_at", "guest_name", "host_name", "listing_title", "payment_status", "funds_status")
        + ("taxable_amount_egp", "vat_calculated_egp", "vat_reversed_egp", "vat_payable_egp"),
        date_basis="payment_created",
        filters=_FIN_FILTERS,
        sortable=("created_at",),
        note="vat_payable_semantics",
        money_columns=(
            "taxable_amount_egp",
            "vat_calculated_egp",
            "vat_reversed_egp",
            "vat_payable_egp",
        ),
        total_labels={
            "vat_calculated_egp": "vat_calculated",
            "vat_reversed_egp": "vat_reversed",
            "vat_payable_egp": "vat_payable",
        },
    ),
    ReportDef(
        "vat_calculated",
        "financial",
        "booking_financials",
        _BOOKING_COLS + ("taxable_amount_egp", "vat_egp", "guest_total_egp", "funds_status"),
        date_basis="booking_created",
        filters=_FIN_FILTERS,
        note="vat_calculated_semantics",
        money_columns=("taxable_amount_egp", "vat_egp", "guest_total_egp"),
        total_labels={"vat_egp": "vat_calculated"},
        fixed={"share": "vat"},
    ),
    ReportDef(
        "host_earnings",
        "financial",
        "host_earnings",
        (
            "host_id",
            "host_name",
            "bookings_count",
            "host_net_egp",
            "paid_out_egp",
            "pending_payable_egp",
        ),
        date_basis="booking_created",
        filters=_COMMON + ("host_id",),
        money_columns=("host_net_egp", "paid_out_egp", "pending_payable_egp"),
    ),
    ReportDef(
        "guest_payments",
        "financial",
        "payments_list",
        (
            "payment_id",
            "booking_id",
            "created_at",
            "payment_status",
            "payment_method",
            "amount_egp",
            "refund_amount_egp",
            "verified_at",
            "guest_name",
            "host_name",
            "listing_title",
        ),
        date_basis="payment_created",
        filters=_COMMON + ("payment_status", "payment_method", "host_id", "guest_id", "unit_id"),
        sortable=("created_at", "amount_egp"),
        money_columns=("amount_egp", "refund_amount_egp"),
    ),
    ReportDef(
        "refunds",
        "financial",
        "payments_list",
        (
            "payment_id",
            "booking_id",
            "created_at",
            "payment_status",
            "amount_egp",
            "refund_amount_egp",
            "refunded_at",
            "guest_name",
            "listing_title",
        ),
        date_basis="payment_created",
        filters=_COMMON + ("payment_status", "host_id", "guest_id", "unit_id"),
        sortable=("created_at", "refund_amount_egp"),
        money_columns=("amount_egp", "refund_amount_egp"),
        fixed={"refunds_only": True},
    ),
    ReportDef(
        "commercial_adjustments",
        "financial",
        "adjustments_list",
        (
            "adjustment_id",
            "created_at",
            "booking_id",
            "adjustment_type",
            "category",
            "amount_egp",
            "status",
            "reason",
        ),
        date_basis="adjustment_created",
        filters=_COMMON + ("status", "host_id", "guest_id"),
        sortable=("created_at", "amount_egp"),
        money_columns=("amount_egp",),
    ),
    # ---- F. Payments -----------------------------------------------------
    ReportDef(
        "payment_transactions",
        "payments",
        "transactions_list",
        (
            "transaction_id",
            "created_at",
            "transaction_type",
            "booking_id",
            "amount_egp",
            "status",
            "provider",
        ),
        date_basis="transaction_created",
        filters=_COMMON + ("status",),
        sortable=("created_at", "amount_egp"),
        money_columns=("amount_egp",),
    ),
    ReportDef(
        "payment_status",
        "payments",
        "payments_grouped",
        ("payment_status", "payment_method", "count", "amount_egp"),
        date_basis="payment_created",
        filters=_COMMON,
        money_columns=("count", "amount_egp"),
    ),
    ReportDef(
        "failed_payments",
        "payments",
        "payments_list",
        (
            "payment_id",
            "booking_id",
            "created_at",
            "payment_status",
            "payment_method",
            "amount_egp",
            "reject_reason",
            "guest_name",
        ),
        date_basis="payment_created",
        filters=_COMMON + ("payment_method",),
        fixed={"statuses": ("rejected",)},
    ),
    ReportDef(
        "refund_transactions",
        "payments",
        "transactions_list",
        (
            "transaction_id",
            "created_at",
            "transaction_type",
            "booking_id",
            "amount_egp",
            "status",
        ),
        date_basis="transaction_created",
        filters=_COMMON,
        fixed={"transaction_types": ("refund", "escrow_refund")},
    ),
    # ---- G. Payouts ------------------------------------------------------
    ReportDef(
        "payouts",
        "payouts",
        "payouts_list",
        (
            "payout_id",
            "created_at",
            "host_name",
            "amount_egp",
            "payout_status",
            "provider",
            "processed_at",
            "failure_reason",
        ),
        date_basis="payout_requested",
        filters=_COMMON + ("payout_status", "host_id"),
        sortable=("created_at", "amount_egp"),
        money_columns=("amount_egp",),
    ),
    ReportDef(
        "pending_payouts",
        "payouts",
        "payouts_list",
        ("payout_id", "created_at", "host_name", "amount_egp", "payout_status"),
        date_basis="payout_requested",
        filters=_COMMON + ("host_id",),
        money_columns=("amount_egp",),
        fixed={"statuses": ("pending", "processing")},
    ),
    ReportDef(
        "paid_payouts",
        "payouts",
        "payouts_list",
        ("payout_id", "created_at", "host_name", "amount_egp", "payout_status", "processed_at"),
        date_basis="payout_processed",
        filters=_COMMON + ("host_id",),
        money_columns=("amount_egp",),
        fixed={"statuses": ("completed",)},
    ),
    ReportDef(
        "failed_payouts",
        "payouts",
        "payouts_list",
        ("payout_id", "created_at", "host_name", "amount_egp", "payout_status", "failure_reason"),
        date_basis="payout_requested",
        filters=_COMMON + ("host_id",),
        fixed={"statuses": ("failed",)},
    ),
    # ---- H. Operations ----------------------------------------------------
    ReportDef(
        "operational_bookings",
        "operations",
        "bookings_list",
        _BOOKING_COLS + ("checked_in_at", "checked_out_at"),
        date_basis="booking_created",
        filters=_BOOKING_FILTERS + ("stay_in_range", "stay_phase"),
        sortable=("created_at", "check_in", "check_out"),
    ),
    ReportDef(
        "check_in",
        "operations",
        "bookings_list",
        _BOOKING_COLS + ("checked_in_at",),
        date_basis="check_in_date",
        filters=("date_from", "date_to", "status", "host_id", "governorate", "city"),
        sortable=("check_in",),
        fixed={"date_field": "check_in"},
    ),
    ReportDef(
        "check_out",
        "operations",
        "bookings_list",
        _BOOKING_COLS + ("checked_out_at",),
        date_basis="check_out_date",
        filters=("date_from", "date_to", "status", "host_id", "governorate", "city"),
        sortable=("check_out",),
        fixed={"date_field": "check_out"},
    ),
    ReportDef(
        "operational_exceptions",
        "operations",
        "exceptions_list",
        (
            "booking_id",
            "created_at",
            "check_in",
            "check_out",
            "status",
            "stay_phase",
            "guest_name",
            "host_name",
            "listing_title",
            "exception",
        ),
        date_basis="booking_created",
        filters=_BOOKING_FILTERS,
    ),
    # ---- I. Trust (under Users & Trust) ------------------------------------
    ReportDef(
        "automated_verification",
        "users_trust",
        "provider_docs",
        (
            "document_id",
            "created_at",
            "user_name",
            "provider",
            "status",
            "updated_at",
        ),
        date_basis="document_created",
        filters=_COMMON + ("status",),
    ),
    ReportDef(
        "manual_review_cases",
        "users_trust",
        "manual_review_docs",
        (
            "document_id",
            "created_at",
            "user_name",
            "document_type",
            "status",
            "provider",
        ),
        date_basis="document_created",
        filters=_COMMON + ("status",),
    ),
    # ---- J. Disputes -------------------------------------------------------
    ReportDef(
        "disputes",
        "disputes",
        "disputes_list",
        (
            "dispute_id",
            "created_at",
            "booking_id",
            "category",
            "status",
            "resolved_at",
        ),
        date_basis="dispute_created",
        filters=_COMMON + ("status",),
        sortable=("created_at",),
    ),
    ReportDef(
        "dispute_resolution",
        "disputes",
        "disputes_grouped",
        ("status", "category", "count"),
        date_basis="dispute_created",
        filters=_COMMON,
    ),
    # ---- K. Reviews --------------------------------------------------------
    ReportDef(
        "reviews",
        "reviews",
        "reviews_list",
        (
            "review_id",
            "created_at",
            "booking_id",
            "listing_title",
            "reviewer_role",
            "rating",
            "is_hidden",
            "published_at",
        ),
        date_basis="review_created",
        filters=_COMMON + ("unit_id",),
        sortable=("created_at", "rating"),
    ),
    ReportDef(
        "ratings",
        "reviews",
        "ratings_grouped",
        ("listing_title", "unit_id", "reviews_count", "avg_rating"),
        date_basis="review_created",
        filters=_COMMON,
    ),
    ReportDef(
        "moderation_status",
        "reviews",
        "moderation_list",
        (
            "report_id",
            "created_at",
            "review_id",
            "reason",
            "status",
            "resolved_at",
        ),
        date_basis="report_created",
        filters=_COMMON + ("status",),
    ),
)

BY_KEY = {r.key: r for r in CATALOG}
